import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "1rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      fontFamily: {
        sans: ['Lexend', 'system-ui', 'sans-serif'],
        display: ['Lexend', 'system-ui', 'sans-serif'],
        "label-xl": ["Lexend"],
        "body-md": ["Lexend"],
        "headline-lg": ["Lexend"],
        "headline-xl": ["Lexend"],
        "label-md": ["Lexend"],
        "headline-md": ["Lexend"],
        "body-lg": ["Lexend"],
      },
      colors: {
        "surface-dim": "#131313",
        "surface-bright": "#393939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#e4bfb1",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        "outline": "#ab8a7d",
        "outline-variant": "#5b4137",
        "surface-tint": "#ffb599",
        "on-primary": "#5a1c00",
        "primary-container": "#ff5f00",
        "on-primary-container": "#531a00",
        "inverse-primary": "#a63b00",
        "on-secondary": "#690000",
        "secondary-container": "#d30000",
        "on-secondary-container": "#ffe2dd",
        "on-tertiary": "#412d00",
        "tertiary-container": "#c08a00",
        "on-tertiary-container": "#3c2900",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#ffdbce",
        "primary-fixed-dim": "#ffb599",
        "on-primary-fixed": "#370e00",
        "on-primary-fixed-variant": "#7f2b00",
        "secondary-fixed": "#ffdad4",
        "secondary-fixed-dim": "#ffb4a8",
        "on-secondary-fixed": "#410000",
        "on-secondary-fixed-variant": "#930000",
        "tertiary-fixed": "#ffdea8",
        "tertiary-fixed-dim": "#ffba20",
        "on-tertiary-fixed": "#271900",
        "on-tertiary-fixed-variant": "#5e4200",
        "on-background": "#e5e2e1",
        "surface-variant": "#353534",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          glow: "hsl(var(--primary-glow))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        info: {
          DEFAULT: "hsl(var(--info))",
          foreground: "hsl(var(--info-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        surface: {
          DEFAULT: "hsl(var(--surface))",
          low: "hsl(var(--surface-low))",
          high: "hsl(var(--surface-high))",
          highest: "hsl(var(--surface-highest))",
          bright: "hsl(var(--surface-bright))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },

      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        "touch-target-min": "56px",
        "unit": "4px",
        "stack-lg": "32px",
        "margin-main": "20px",
        "gutter-card": "16px",
        "stack-md": "16px",
        "stack-sm": "8px",
      },
      fontSize: {
        "label-xl": ["20px", {"lineHeight": "24px", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-lg": ["28px", {"lineHeight": "34px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "headline-xl": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "label-md": ["14px", {"lineHeight": "18px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-md": ["22px", {"lineHeight": "28px", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "26px", "fontWeight": "500"}],
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-in": { from: { opacity: "0", transform: "translateY(8px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "pulse-glow": {
          "0%, 100%": { boxShadow: "0 0 0 0 hsl(var(--primary) / 0.5)" },
          "50%": { boxShadow: "0 0 0 12px hsl(var(--primary) / 0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.4s cubic-bezier(0.4,0,0.2,1)",
        "pulse-glow": "pulse-glow 2s ease-out infinite",
      },
    },
  },
  plugins: [tailwindcssAnimate],
} satisfies Config;
