// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-platforms.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-platforms.ts
var list_platforms_default = defineTool({
  name: "list_platforms",
  title: "Listar plataformas",
  description: "Lista as plataformas de entrega cadastradas pelo motorista autenticado.",
  inputSchema: {
    only_active: z.boolean().optional().describe("Se verdadeiro, retorna apenas plataformas ativas.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ only_active }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("platforms").select("id, name, segment, payment_model, cycle, active").order("name");
    if (only_active) query = query.eq("active", true);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { platforms: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-routes.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var list_routes_default = defineTool2({
  name: "list_routes",
  title: "Listar rotas",
  description: "Lista as rotas/corridas do motorista autenticado em um intervalo de datas, com valor, dist\xE2ncia e pacotes.",
  inputSchema: {
    since: z2.string().optional().describe("Data inicial ISO (ex.: 2026-08-01). Padr\xE3o: \xFAltimos 30 dias."),
    until: z2.string().optional().describe("Data final ISO (ex.: 2026-08-31)."),
    limit: z2.number().int().optional().describe("M\xE1ximo de registros (padr\xE3o 50, teto 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ since, until, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const start = since ?? new Date(Date.now() - 30 * 864e5).toISOString().slice(0, 10);
    const max = Math.min(Math.max(limit ?? 50, 1), 200);
    let query = supabase.from("routes").select(
      "id, occurred_at, amount, tip, distance_km, package_count, product_type, origin, destination, platform_id, started_at, ended_at, break_minutes"
    ).gte("occurred_at", start).order("occurred_at", { ascending: false }).limit(max);
    if (until) query = query.lte("occurred_at", until);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { routes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-expenses.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var list_expenses_default = defineTool3({
  name: "list_expenses",
  title: "Listar despesas",
  description: "Lista as despesas do motorista autenticado (combust\xEDvel, manuten\xE7\xE3o, alimenta\xE7\xE3o) em um intervalo de datas.",
  inputSchema: {
    category: z3.enum(["combustivel", "manutencao", "alimentacao"]).optional().describe("Filtra por categoria de despesa."),
    since: z3.string().optional().describe("Data inicial ISO. Padr\xE3o: \xFAltimos 30 dias."),
    until: z3.string().optional().describe("Data final ISO."),
    limit: z3.number().int().optional().describe("M\xE1ximo de registros (padr\xE3o 50, teto 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, since, until, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const start = since ?? new Date(Date.now() - 30 * 864e5).toISOString().slice(0, 10);
    const max = Math.min(Math.max(limit ?? 50, 1), 200);
    let query = supabase.from("expenses").select(
      "id, occurred_at, title, category, amount, liters, price_per_liter, is_full_tank, odometer_km, vendor, payment_method, installment_number, installment_total"
    ).gte("occurred_at", start).order("occurred_at", { ascending: false }).limit(max);
    if (category) query = query.eq("category", category);
    if (until) query = query.lte("occurred_at", until);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { expenses: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-expense.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var create_expense_default = defineTool4({
  name: "create_expense",
  title: "Registrar despesa",
  description: "Registra uma nova despesa (combust\xEDvel, manuten\xE7\xE3o ou alimenta\xE7\xE3o) para o motorista autenticado.",
  inputSchema: {
    title: z4.string().describe("Descri\xE7\xE3o curta da despesa."),
    amount: z4.number().describe("Valor em reais."),
    category: z4.enum(["combustivel", "manutencao", "alimentacao"]).describe("Categoria da despesa."),
    occurred_at: z4.string().optional().describe("Data/hora ISO. Padr\xE3o: agora."),
    liters: z4.number().optional().describe("Litros abastecidos (combust\xEDvel)."),
    is_full_tank: z4.boolean().optional().describe("Se o abastecimento completou o tanque."),
    odometer_km: z4.number().optional().describe("Hod\xF4metro no momento da despesa."),
    vendor: z4.string().optional().describe("Empresa/posto onde a despesa ocorreu."),
    payment_method: z4.enum(["dinheiro", "pix", "cartao"]).optional().describe("Forma de pagamento.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("expenses").insert({
      user_id: ctx.getUserId(),
      title: input.title,
      amount: input.amount,
      category: input.category,
      occurred_at: input.occurred_at ?? (/* @__PURE__ */ new Date()).toISOString(),
      liters: input.liters ?? null,
      is_full_tank: input.is_full_tank ?? false,
      odometer_km: input.odometer_km ?? null,
      vendor: input.vendor ?? null,
      payment_method: input.payment_method ?? null
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { expense: data }
    };
  }
});

// src/lib/mcp/tools/list-work-sessions.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^4.4.3";
var list_work_sessions_default = defineTool5({
  name: "list_work_sessions",
  title: "Listar horas trabalhadas",
  description: "Lista as sess\xF5es de trabalho (horas trabalhadas) do motorista autenticado em um intervalo de datas.",
  inputSchema: {
    since: z5.string().optional().describe("Data inicial ISO. Padr\xE3o: \xFAltimos 30 dias."),
    until: z5.string().optional().describe("Data final ISO."),
    limit: z5.number().int().optional().describe("M\xE1ximo de registros (padr\xE3o 50, teto 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ since, until, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const start = since ?? new Date(Date.now() - 30 * 864e5).toISOString().slice(0, 10);
    const max = Math.min(Math.max(limit ?? 50, 1), 200);
    let query = supabase.from("work_sessions").select("id, started_at, ended_at, break_minutes, start_km, end_km, platform_id, product_type, notes").gte("started_at", start).order("started_at", { ascending: false }).limit(max);
    if (until) query = query.lte("started_at", until);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const sessions = (data ?? []).map((s) => {
      const minutes = s.ended_at ? Math.max(
        0,
        (new Date(s.ended_at).getTime() - new Date(s.started_at).getTime()) / 6e4 - (s.break_minutes ?? 0)
      ) : null;
      return { ...s, worked_hours: minutes === null ? null : Number((minutes / 60).toFixed(2)) };
    });
    return {
      content: [{ type: "text", text: JSON.stringify(sessions) }],
      structuredContent: { work_sessions: sessions }
    };
  }
});

// src/lib/mcp/tools/earnings-summary.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^4.4.3";
var earnings_summary_default = defineTool6({
  name: "earnings_summary",
  title: "Resumo financeiro",
  description: "Resumo de receita, despesas, lucro, KM rodados e horas trabalhadas do motorista autenticado em um per\xEDodo.",
  inputSchema: {
    since: z6.string().optional().describe("Data inicial ISO. Padr\xE3o: \xFAltimos 30 dias."),
    until: z6.string().optional().describe("Data final ISO. Padr\xE3o: hoje.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ since, until }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const start = since ?? new Date(Date.now() - 30 * 864e5).toISOString().slice(0, 10);
    const end = until ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const endBound = `${end}T23:59:59.999Z`;
    const [routes, dailies, expenses, sessions] = await Promise.all([
      supabase.from("routes").select("amount, tip, distance_km").gte("occurred_at", start).lte("occurred_at", endBound),
      supabase.from("daily_totals").select("amount, distance_km").gte("occurred_at", start).lte("occurred_at", endBound),
      supabase.from("expenses").select("amount, category").gte("occurred_at", start).lte("occurred_at", endBound),
      supabase.from("work_sessions").select("started_at, ended_at, break_minutes").gte("started_at", start).lte("started_at", endBound)
    ]);
    const firstError = routes.error ?? dailies.error ?? expenses.error ?? sessions.error;
    if (firstError) return { content: [{ type: "text", text: firstError.message }], isError: true };
    const revenue = (routes.data ?? []).reduce((sum, r) => sum + Number(r.amount ?? 0) + Number(r.tip ?? 0), 0) + (dailies.data ?? []).reduce((sum, d) => sum + Number(d.amount ?? 0), 0);
    const distance_km = (routes.data ?? []).reduce((sum, r) => sum + Number(r.distance_km ?? 0), 0) + (dailies.data ?? []).reduce((sum, d) => sum + Number(d.distance_km ?? 0), 0);
    const byCategory = {};
    let expenseTotal = 0;
    for (const e of expenses.data ?? []) {
      const amount = Number(e.amount ?? 0);
      expenseTotal += amount;
      byCategory[e.category] = (byCategory[e.category] ?? 0) + amount;
    }
    const hours = (sessions.data ?? []).reduce((sum, s) => {
      if (!s.ended_at) return sum;
      const minutes = (new Date(s.ended_at).getTime() - new Date(s.started_at).getTime()) / 6e4 - (s.break_minutes ?? 0);
      return sum + Math.max(0, minutes) / 60;
    }, 0);
    const round = (n) => Number(n.toFixed(2));
    const summary = {
      period: { since: start, until: end },
      revenue: round(revenue),
      expenses: round(expenseTotal),
      expenses_by_category: Object.fromEntries(Object.entries(byCategory).map(([k, v]) => [k, round(v)])),
      profit: round(revenue - expenseTotal),
      distance_km: round(distance_km),
      worked_hours: round(hours),
      revenue_per_km: distance_km > 0 ? round(revenue / distance_km) : null,
      revenue_per_hour: hours > 0 ? round(revenue / hours) : null,
      routes_count: (routes.data ?? []).length
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "tkktqdxdshmkwdfvfpez";
var mcp_default = defineMcp({
  name: "pocket-pwa-builder",
  title: "Pocket PWA Builder",
  version: "0.1.0",
  instructions: "Ferramentas do Driver Hub, app de gest\xE3o financeira para motoristas/entregadores. Use `earnings_summary` para receita, despesas, lucro, KM e horas em um per\xEDodo; `list_routes`, `list_expenses` e `list_work_sessions` para registros detalhados; `list_platforms` para as plataformas cadastradas; `create_expense` para registrar uma nova despesa. Valores em reais (BRL), datas em ISO.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    earnings_summary_default,
    list_routes_default,
    list_expenses_default,
    create_expense_default,
    list_work_sessions_default,
    list_platforms_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
